In [1]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
from google.colab import files
Uploaded=files.upload()

Saving 1.csv to 1.csv


In [9]:
dataset= pd.read_csv('1.csv')
dataset


CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0           619    France  Female  ...               1        101348.88       1
1           608     Spain  Female  ...               1        112542.58       0
2           502    France  Female  ...               0        113931.57       1
3           699    France  Female  ...               0         93826.63       0
4           850     Spain  Female  ...               1         79084.10       0
..          ...       ...     ...  ...             ...              ...     ...
58          511     Spain  Female  ...               0          1643.11       1
59          614    France    Male  ...               1         46775.28       0
60          742    France    Male  ...               0         84509.57       0
61          687    France  Female  ...               0        126494.82       0
62          555     Spain    Male  ...               0        178798.13       0

[63 rows x 10 columns]

In [10]:
#Check Missing Data
dataset.isnull().sum()

CreditScore        0
Geography          0
Gender             2
Age                2
Tenure             1
Balance            6
HasCrCard          2
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      63 non-null     int64  
 1   Geography        63 non-null     object 
 2   Gender           61 non-null     object 
 3   Age              61 non-null     float64
 4   Tenure           62 non-null     float64
 5   Balance          57 non-null     float64
 6   HasCrCard        61 non-null     float64
 7   IsActiveMember   63 non-null     int64  
 8   EstimatedSalary  63 non-null     float64
 9   Exited           63 non-null     int64  
dtypes: float64(5), int64(3), object(2)
memory usage: 5.0+ KB


In [15]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:8].values
# Extracting dependent variable:
y = dataset.iloc[:,9].values

In [16]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NaN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:,3:9]) 
#Replacing missing data with the calculated mean value  
X[:,3:9]= imputer.transform(X[:,3:9])  

In [17]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NaN, strategy= 'constant', fill_value='female', verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 2:3]) 
#Replacing missing data with the constant value  
X[:, 2:3]= imputer.transform(X[:,2:3])  

In [19]:
print(X)

[[619 'France' 'Female' 42.0 2.0 0.0 1.0 1.0]
 [608 'Spain' 'Female' 41.0 1.0 83807.86 0.0 1.0]
 [502 'France' 'Female' 42.0 8.0 159660.8 1.0 0.0]
 [699 'France' 'Female' 39.0 1.0 0.0 0.0 0.0]
 [850 'Spain' 'Female' 43.0 2.0 125510.82 1.0 1.0]
 [645 'Spain' 'Male' 44.0 8.0 113755.78 1.0 0.0]
 [822 'France' 'Male' 50.0 7.0 0.0 1.0 1.0]
 [376 'France' 'Female' 29.0 4.0 115046.74 1.0 0.0]
 [501 'France' 'Male' 44.0 4.0 142051.07 0.6229508196721312 1.0]
 [684 'France' 'Male' 27.0 2.0 134603.88 1.0 1.0]
 [528 'France' 'Male' 31.0 6.0 102016.72 0.0 0.0]
 [497 'Spain' 'Male' 24.0 3.0 0.0 1.0 0.0]
 [476 'France' 'Female' 34.0 4.709677419354839 0.0 1.0 0.0]
 [549 'France' 'Female' 25.0 5.0 0.0 0.0 0.0]
 [635 'Spain' 'Female' 35.0 7.0 0.0 1.0 1.0]
 [616 'France' 'Male' 45.0 3.0 143129.41 0.6229508196721312 1.0]
 [653 'France' 'Male' 58.0 1.0 132602.88 1.0 0.0]
 [549 'Spain' 'Female' 24.0 9.0 0.0 1.0 1.0]
 [587 'Spain' 'female' 45.0 6.0 0.0 0.0 0.0]
 [726 'France' 'Female' 24.0 6.0 0.0 1.0 1.0]
 

In [20]:
print(y)

[1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0]


In [21]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])

In [22]:
print(X)

[[619 0 'Female' 42.0 2.0 0.0 1.0 1.0]
 [608 1 'Female' 41.0 1.0 83807.86 0.0 1.0]
 [502 0 'Female' 42.0 8.0 159660.8 1.0 0.0]
 [699 0 'Female' 39.0 1.0 0.0 0.0 0.0]
 [850 1 'Female' 43.0 2.0 125510.82 1.0 1.0]
 [645 1 'Male' 44.0 8.0 113755.78 1.0 0.0]
 [822 0 'Male' 50.0 7.0 0.0 1.0 1.0]
 [376 0 'Female' 29.0 4.0 115046.74 1.0 0.0]
 [501 0 'Male' 44.0 4.0 142051.07 0.6229508196721312 1.0]
 [684 0 'Male' 27.0 2.0 134603.88 1.0 1.0]
 [528 0 'Male' 31.0 6.0 102016.72 0.0 0.0]
 [497 1 'Male' 24.0 3.0 0.0 1.0 0.0]
 [476 0 'Female' 34.0 4.709677419354839 0.0 1.0 0.0]
 [549 0 'Female' 25.0 5.0 0.0 0.0 0.0]
 [635 1 'Female' 35.0 7.0 0.0 1.0 1.0]
 [616 0 'Male' 45.0 3.0 143129.41 0.6229508196721312 1.0]
 [653 0 'Male' 58.0 1.0 132602.88 1.0 0.0]
 [549 1 'Female' 24.0 9.0 0.0 1.0 1.0]
 [587 1 'female' 45.0 6.0 0.0 0.0 0.0]
 [726 0 'Female' 24.0 6.0 0.0 1.0 1.0]
 [732 0 'Male' 41.0 8.0 0.0 1.0 1.0]
 [636 1 'Female' 32.0 8.0 0.0 1.0 0.0]
 [510 1 'Female' 38.0 4.0 0.0 1.0 0.0]
 [669 0 'Male' 46.0

In [23]:
print(X)

[[619 0 'Female' 42.0 2.0 0.0 1.0 1.0]
 [608 1 'Female' 41.0 1.0 83807.86 0.0 1.0]
 [502 0 'Female' 42.0 8.0 159660.8 1.0 0.0]
 [699 0 'Female' 39.0 1.0 0.0 0.0 0.0]
 [850 1 'Female' 43.0 2.0 125510.82 1.0 1.0]
 [645 1 'Male' 44.0 8.0 113755.78 1.0 0.0]
 [822 0 'Male' 50.0 7.0 0.0 1.0 1.0]
 [376 0 'Female' 29.0 4.0 115046.74 1.0 0.0]
 [501 0 'Male' 44.0 4.0 142051.07 0.6229508196721312 1.0]
 [684 0 'Male' 27.0 2.0 134603.88 1.0 1.0]
 [528 0 'Male' 31.0 6.0 102016.72 0.0 0.0]
 [497 1 'Male' 24.0 3.0 0.0 1.0 0.0]
 [476 0 'Female' 34.0 4.709677419354839 0.0 1.0 0.0]
 [549 0 'Female' 25.0 5.0 0.0 0.0 0.0]
 [635 1 'Female' 35.0 7.0 0.0 1.0 1.0]
 [616 0 'Male' 45.0 3.0 143129.41 0.6229508196721312 1.0]
 [653 0 'Male' 58.0 1.0 132602.88 1.0 0.0]
 [549 1 'Female' 24.0 9.0 0.0 1.0 1.0]
 [587 1 'female' 45.0 6.0 0.0 0.0 0.0]
 [726 0 'Female' 24.0 6.0 0.0 1.0 1.0]
 [732 0 'Male' 41.0 8.0 0.0 1.0 1.0]
 [636 1 'Female' 32.0 8.0 0.0 1.0 0.0]
 [510 1 'Female' 38.0 4.0 0.0 1.0 0.0]
 [669 0 'Male' 46.0

In [24]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 2] = labelencoder_X.fit_transform(X[:, 2])

In [25]:
print(X)

[[619 0 0 42.0 2.0 0.0 1.0 1.0]
 [608 1 0 41.0 1.0 83807.86 0.0 1.0]
 [502 0 0 42.0 8.0 159660.8 1.0 0.0]
 [699 0 0 39.0 1.0 0.0 0.0 0.0]
 [850 1 0 43.0 2.0 125510.82 1.0 1.0]
 [645 1 1 44.0 8.0 113755.78 1.0 0.0]
 [822 0 1 50.0 7.0 0.0 1.0 1.0]
 [376 0 0 29.0 4.0 115046.74 1.0 0.0]
 [501 0 1 44.0 4.0 142051.07 0.6229508196721312 1.0]
 [684 0 1 27.0 2.0 134603.88 1.0 1.0]
 [528 0 1 31.0 6.0 102016.72 0.0 0.0]
 [497 1 1 24.0 3.0 0.0 1.0 0.0]
 [476 0 0 34.0 4.709677419354839 0.0 1.0 0.0]
 [549 0 0 25.0 5.0 0.0 0.0 0.0]
 [635 1 0 35.0 7.0 0.0 1.0 1.0]
 [616 0 1 45.0 3.0 143129.41 0.6229508196721312 1.0]
 [653 0 1 58.0 1.0 132602.88 1.0 0.0]
 [549 1 0 24.0 9.0 0.0 1.0 1.0]
 [587 1 2 45.0 6.0 0.0 0.0 0.0]
 [726 0 0 24.0 6.0 0.0 1.0 1.0]
 [732 0 1 41.0 8.0 0.0 1.0 1.0]
 [636 1 0 32.0 8.0 0.0 1.0 0.0]
 [510 1 0 38.0 4.0 0.0 1.0 0.0]
 [669 0 1 46.0 3.0 0.0 0.0 1.0]
 [846 0 2 38.0 5.0 0.0 1.0 1.0]
 [577 0 1 25.0 3.0 0.0 0.0 1.0]
 [756 0 1 36.0 2.0 136815.64 1.0 1.0]
 [571 0 1 44.0 9.0 0.0 0.0 0

In [26]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [27]:
print(X_train)

[[585 0 1 36.0 5.0 146050.97 0.0 0.0]
 [549 1 0 24.0 9.0 0.0 1.0 1.0]
 [669 0 1 46.0 3.0 0.0 0.0 1.0]
 [822 0 1 50.0 7.0 0.0 1.0 1.0]
 [846 0 2 38.0 5.0 0.0 1.0 1.0]
 [502 0 0 42.0 8.0 159660.8 1.0 0.0]
 [726 0 0 24.0 6.0 0.0 1.0 1.0]
 [555 1 1 38.80327868852459 1.0 56084.69 0.0 0.0]
 [411 0 1 29.0 0.0 68372.54684210526 1.0 1.0]
 [533 0 1 36.0 7.0 85311.7 0.0 1.0]
 [850 1 0 43.0 2.0 125510.82 1.0 1.0]
 [553 0 1 38.80327868852459 9.0 110112.54 0.0 0.0]
 [619 0 0 42.0 2.0 0.0 1.0 1.0]
 [756 0 1 36.0 2.0 136815.64 1.0 1.0]
 [645 1 1 44.0 8.0 113755.78 1.0 0.0]
 [687 0 0 27.0 9.0 152328.88 0.0 0.0]
 [660 1 0 61.0 5.0 155931.11 1.0 1.0]
 [511 1 0 66.0 4.0 0.0 1.0 0.0]
 [472 1 1 40.0 4.0 0.0 1.0 0.0]
 [656 0 1 45.0 5.0 127864.4 1.0 0.0]
 [587 1 2 45.0 6.0 0.0 0.0 0.0]
 [510 1 0 38.0 4.0 0.0 1.0 0.0]
 [732 0 1 41.0 8.0 0.0 1.0 1.0]
 [698 0 1 44.0 10.0 116363.37 1.0 0.0]
 [608 1 0 41.0 1.0 83807.86 0.0 1.0]
 [497 1 1 24.0 3.0 0.0 1.0 0.0]
 [549 0 0 25.0 5.0 0.0 0.0 0.0]
 [788 0 0 33.0 5.0 0.0 

In [28]:
print(X_test)

[[574 0 0 43.0 3.0 68372.54684210526 1.0 1.0]
 [636 1 0 32.0 8.0 0.0 1.0 0.0]
 [776 0 0 32.0 4.0 109421.13 1.0 1.0]
 [829 0 0 27.0 9.0 68372.54684210526 1.0 1.0]
 [520 1 0 42.0 6.0 0.0 1.0 1.0]
 [804 1 1 33.0 7.0 76548.6 0.0 1.0]
 [619 0 1 43.0 1.0 125211.92 1.0 1.0]
 [528 0 1 31.0 6.0 102016.72 0.0 0.0]
 [834 0 0 49.0 2.0 131394.56 0.0 0.0]
 [722 1 0 29.0 9.0 0.0 1.0 1.0]
 [699 0 0 39.0 1.0 0.0 0.0 0.0]
 [577 0 1 25.0 3.0 0.0 0.0 1.0]
 [465 0 0 51.0 8.0 122522.32 0.0 0.0]
 [556 0 0 61.0 2.0 68372.54684210526 1.0 1.0]
 [742 0 1 35.0 5.0 136857.0 0.0 0.0]
 [614 0 1 51.0 4.0 40685.92 1.0 1.0]]


In [29]:
print(y_test)

[0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0]


In [30]:
print(y_train)

[0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0
 0 0 0 0 1 1 0 1 0 1]


In [31]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
print(X_train)

[[-0.28332402 -0.65133895  0.64345949 -0.29935278  0.12312713  1.24571694
  -1.37387191 -0.93808315]
 [-0.59767434  1.53529895 -1.13551675 -1.60202581  1.54408734 -1.12517379
   0.76102823  1.06600358]
 [ 0.45016006 -0.65133895  0.64345949  0.78620808 -0.58735298 -1.12517379
  -1.37387191  1.06600358]
 [ 1.78614893 -0.65133895  0.64345949  1.22043243  0.83360723 -1.12517379
   0.76102823  1.06600358]
 [ 1.99571581 -0.65133895  2.42243573 -0.08224061  0.12312713 -1.12517379
   0.76102823  1.06600358]
 [-1.00807615 -0.65133895 -1.13551675  0.35198374  1.18884728  1.46664953
   0.76102823 -0.93808315]
 [ 0.94788141 -0.65133895 -1.13551675 -1.60202581  0.47836718 -1.12517379
   0.76102823  1.06600358]
 [-0.54528262  1.53529895  0.64345949  0.00496018 -1.29783308 -0.21473361
  -1.37387191 -0.93808315]
 [-1.80268391 -0.65133895  0.64345949 -1.05924538 -1.65307313 -0.01526102
   0.76102823  1.06600358]
 [-0.73738559 -0.65133895  0.64345949 -0.29935278  0.83360723  0.25971751
  -1.37387191  1.

In [33]:
print(X_test)

[[-0.37937551 -0.65133895 -1.13551675  0.46053982 -0.58735298 -0.01526102
   0.76102823  1.06600358]
 [ 0.1620056   1.53529895 -1.13551675 -0.73357712  1.18884728 -1.12517379
   0.76102823 -0.93808315]
 [ 1.38447907 -0.65133895 -1.13551675 -0.73357712 -0.23211292  0.65109337
   0.76102823  1.06600358]
 [ 1.8472726  -0.65133895 -1.13551675 -1.27635756  1.54408734 -0.01526102
   0.76102823  1.06600358]
 [-0.85090099  1.53529895 -1.13551675  0.35198374  0.47836718 -1.12517379
   0.76102823  1.06600358]
 [ 1.62897377  1.53529895  0.64345949 -0.62502104  0.83360723  0.11746339
  -1.37387191  1.06600358]
 [ 0.0135624  -0.65133895  0.64345949  0.46053982 -1.29783308  0.90743017
   0.76102823  1.06600358]
 [-0.78104536 -0.65133895  0.64345949 -0.84213321  0.47836718  0.53089529
  -1.37387191 -0.93808315]
 [ 1.89093237 -0.65133895 -1.13551675  1.11187634 -0.94259303  1.00779488
  -1.37387191 -0.93808315]
 [ 0.91295359  1.53529895 -1.13551675 -1.05924538  1.54408734 -1.12517379
   0.76102823  1.

In [53]:

# Fitting Decision Tree Classification to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [54]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [55]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[12  1]
 [ 2  1]]


In [56]:
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 82/100

from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 81.25


In [38]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives) 
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/30
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision))

Precision: 0.00


In [39]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/23+11
recall = recall_score(y_test, y_pred, average='macro')
print('Recall: %.3f' % (recall))

Recall: 0.308


In [40]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# (2*0.829*0.906)/0.829+0.906
# calculate score
score = f1_score(y_test, y_pred, average='macro')
print('F-Measure: %.3f' % (score*100))

F-Measure: 33.333


In [57]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/manisha_model.pkl', 'wb')) 
# Saving model to disk
 

  


[INFO] Saving model...


In [58]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/manisha_model.pkl','rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [59]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/manisha_model.sav'
joblib.dump(classifier, filename)
 
# some time later...
 
# load the model from disk
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(result)

0.8125


In [60]:
!pip install streamlit

In [61]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [62]:
# Load the pickled model
import pickle
pickle_in = open("/content/drive/My Drive/manisha_model.pkl","rb")
model=pickle.load(pickle_in)

In [63]:
%%writefile app.py
import streamlit as st 
from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
pickle_in = open("/content/drive/My Drive/manisha_model.pkl","rb")
model=pickle.load(pickle_in)
dataset= pd.read_csv('/content/drive/My Drive/1.csv')
X = dataset.iloc[:,1:9].values

# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NaN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:,3:9]) 
#Replacing missing data with the calculated mean value  
X[:,3:9]= imputer.transform(X[:,3:9])  

# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NaN, strategy= 'constant', fill_value='female', verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 2:3]) 
#Replacing missing data with the constant value  
X[:, 2:3]= imputer.transform(X[:,2:3])  

# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])

# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 2] = labelencoder_X.fit_transform(X[:, 2])

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

def predict_note_authentication(CreditScore,Geography,Gender,Age,Tenure,Balance,HasCrCard,IsActiveMember,EstimatedSalary):
  output= model.predict(sc.transform([[CreditScore,Geography,Gender,Age,Tenure,Balance,HasCrCard,IsActiveMember,EstimatedSalary]]))
  print("Customer will leave =", output)
  if output==[1]:
    prediction="Customer will Leave"
  else:
    prediction="Customer will not Leave"
  print(prediction)
  return prediction
def main():
    
    html_temp = """
   <div class="" style="background-color:blue;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center> 
   <center><p style="font-size:25px;color:white;margin-top:10px;">Machine Learning Endterm Practical Exam</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    st.header("Customer Prediction")
    Age = st.number_input('Insert a Age',18,60)
    CreditScore= st.number_input('Insert a CreditScore',400,1000)
    HasCrCard = st.number_input('Insert a HasCrCard 0 For No 1 For Yes',0,1)
    Tenure = st.number_input('Insert a Tenure',0,20)
    Balance = st.number_input('Insert a Balance',0)
    Gender = st.number_input('Insert 0 For Male 1 For Female ',0,1)
    Geography= st.number_input('Insert Geography 0 For France 1 For Spain'0,1)
    IsActiveMember= st.number_input('Insert a IsActiveMember 0 For No 1 For Yes',0,1)
    EstimatedSalary= st.number_input('Insert a EstimatedSalary',0)
    
    
    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(CreditScore,Geography,Gender,Age,Tenure,Balance,HasCrCard,IsActiveMember,EstimatedSalary)
      st.success('Model has predicted {}'.format(result))
    if st.button("About"):
      st.subheader("Developed by Manisha Kumawat")
      st.subheader("B-Section,PIET")

if __name__=='__main__':
  main()
   


Overwriting app.py


In [64]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [65]:
!pip install pyngrok


In [72]:
!ngrok authtoken 1utHudl6HJskBWASmlDSSYZo42K_665jAW2DbvMGGmbgAgi8Z


Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [73]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url


<NgrokTunnel: "http://091e61b673da.ngrok.io" -> "http://localhost:80">

In [68]:
 !streamlit run --server.port 80 app.py


  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://34.80.136.129:80

  Stopping...


In [69]:
ngrok.kill()

https://priyanshujainpiet18cs111midter.herokuapp.com